DROP INDEX IF EXISTS idx_lancamentos_loja;
DROP INDEX IF EXISTS idx_produtos_mercearia_loja;
DROP INDEX IF EXISTS idx_produtos_departamento_loja;
DROP INDEX IF EXISTS idx_departamentos_loja;
DROP INDEX IF EXISTS idx_produtos_genericos_loja;
ALTER TABLE lancamentos DROP CONSTRAINT IF EXISTS fk_lancamentos_loja;
ALTER TABLE produtos_mercearia DROP CONSTRAINT IF EXISTS fk_produtos_mercearia_loja;
ALTER TABLE produtos_departamento DROP CONSTRAINT IF EXISTS fk_produtos_departamento_loja;
ALTER TABLE departamentos DROP CONSTRAINT IF EXISTS fk_departamentos_loja;
ALTER TABLE produtos_genericos DROP CONSTRAINT IF EXISTS fk_produtos_genericos_loja;
ALTER TABLE produtos_departamento DROP CONSTRAINT IF EXISTS uk_produto_departamento_loja_codigo;
ALTER TABLE produtos_mercearia DROP CONSTRAINT IF EXISTS uk_produto_mercearia_loja_codigo_barras;
ALTER TABLE produtos_mercearia DROP CONSTRAINT IF EXISTS uk_produto_mercearia_loja_sku;
ALTER TABLE produtos_genericos DROP CONSTRAINT IF EXISTS uk_produtos_genericos_loja_codigo;
ALTER TABLE lancamentos DROP COLUMN IF EXISTS loja_id;
ALTER TABLE produtos_mercearia DROP COLUMN IF EXISTS loja_id;
ALTER TABLE produtos_departamento DROP COLUMN IF EXISTS loja_id;
ALTER TABLE departamentos DROP COLUMN IF EXISTS loja_id;
ALTER TABLE produtos_genericos DROP COLUMN IF EXISTS loja_id;
